services:
#    import.example:
#        class: ImportBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    weather.provider.yahoo:
        class: AppBundle\Providers\YahooWeatherProvider
    weather.provider.openweather:
        class: AppBundle\Providers\OpenMapWeatherProvider
